### PR TITLE
Exclude exceptions of certain types #34

### PR DESCRIPTION
**Pull request by ghost**
Fix for this issue:
https://github.com/cavneb/airbrake-grails/issues/34

### CODE REVIEW

**Comment by ghost** [comment]
If you're happy to merge these, would you be willing to release a new version of the plugin thereafter?

**Comment by ghost** [comment]
I've made 2 commits that address all the issues you raised with this, but I have not yet added any specs. I'm not familiar with Spock so it'll take a while to get these done. If you like, you could review my changes while I'm writing the specs, or just wait until the specs have been committed.

**Comment by jonspalmer** [comment]
Changes look great. Hopefully the specs are easy to write. There are a lot of existing specs to pattern from.

**Comment by ghost** [comment]
I added the specs, so assuming your happy with them, I think this is good to go. If you're happy to merge this, could you also release a new version of the plugin that includes these changes?

**Comment by jonspalmer** [comment]
released as 0.9.3

**Pull request merged**
