### PR TITLE
changes prompted by discussion of issue #31

### PR DESCRIPTION
**Pull request by ghost**
Hi,

I know our discussion didn't reach any firm conclusions about what changes (if any) should be made, but I think this pull request adds some useful features without breaking any existing functionality.

What I've done is added a config param that checks if the airbrake server/plugin configuration are correct on startup and if not, sending notifications is disabled. If this config param is omitted, there are no changes in behaviour.

I've also added a means of enabling/disabling the sending of notifications at runtime. See the changes in `README.md` for a more detailed description of these features

Thanks.

### CODE REVIEW

**Comment by jonspalmer** [comment]
Thinking about the idea of 'enable/disable' the integration based on Airbrake's response I wonder if we might go a little further. It might be nice to be able to register for an event every time a notification is sent to Airbrake. The event would tell you success or failure. That way consumers of the event would be able to apply their own logic as to when to disable or enable the integration. For instance you could count the number of errors and if five in a row fail or >80% are failing over 5 minutes then disable etc. That seems like a more powerful and useful feature than just shutting off if one test notice fails at startup.

**Comment by ghost** [comment]
The changes proposed in your first comment have been committed.

Regarding the event handler you propose in the second comment, how do you see this being implemented? I can think of two options:

### 1. Spring Bean

User defines a Spring bean named "airbrakeObserver" that implements an interface such as

``` groovy
interface AirbrakeObserver {

    /**
     * This method is called back with the result of each Airbrake notification
     * @param notice the notice that was sent to Airbrake
     * @result indicates whether the notice was successfully processed by Airbrake
     */
    void notify(Notice notice, Boolean result)
}
```

The implementation of this interface could dependency-inject the `AirbrakeService` in order to programatically enable/disable sending of notifications

### 2. Configuration

Users adds a Closure in Config.groovy that is called back after each notification is sent, e.g.

``` groovy
grails.plugins.airbrake.notify = {AirbrakeService airbrakeService, Notice notice, Boolean result ->
    if (!result) {
        airbrakeService.setEnabled(false)
    }
}
```

Do you have a preference for either of the above, or perhaps another suggestion?

**Comment by ghost** [comment]
Just in case there's any confusion kaufda and domurtag are in fact the same person.

**Comment by jonspalmer** [comment]
The two options you outlined are pretty much what I had in mind. The closure in configuration is probably the simplest to implement but hard to test (you potentially up up with a bunch of business logic in Config.groovy). The spring bean approach seems a bit more complicated but more complete. I'd like to think a little more about how it actually get configured and wired up. Perhaps we should create a new pull request for that feature.

**Pull request merged**
