### PR TITLE
resolved #19 and #20

### LINKED ISSUE #19: filter stacktraces
Before the stacktrace is converted to XML, remove all the Groovy/Grails noise from it with

``` groovy
Throwable filtered = new DefaultStackTraceFilterer().filter(unfilteredThrowable)
```

### PR DESCRIPTION
**Pull request by ghost**
Here's my 2nd attempt at #19 and #20. I've taken into consideration the comments you made on my previous submission

### CODE REVIEW

**Comment by jonspalmer** [comment]
There are a bunch of things going on in this pull request. #19, #20, an upgrade to 2.1.1 and some extra logging. It would  me much easier to submit separate pull requests that can be considered independently. There are some questions still around the thread pooling solution that prevent me from accepting the other much more straight forward changes.

Also a general practice for many open source projects is NOT to include version changes in pull requests. Its normally much easier for the project committers to increment version numbers as they package a release. I'd suggest we follow that pattern here.

**Comment by ghost** [comment]
> I'd be happy to code a solution of that myself 

I agree that it makes sense to integrate this with the existing async closure handling if that's possible (I haven't really looked at how this works, to be honest). If you're offering to do this, I'm happy to accept

**Comment by ghost** [comment]
> Also a general practice for many open source projects is NOT to include version changes in pull requests. Its 
> normally much easier for the project committers to increment version numbers as they package a release. I'd 
> suggest we follow that pattern here.

That seems like a sensible practice, I'll revert the project version change and the Grails upgrade

**Comment by ghost** [comment]
Further to your comments regarding this pull request, I've made the following changes:
- reverted upgrade to Grails 2.1.1
- reverted change to plugin version
- fixed bug with asynchronous notification sending

I think that's everything apart from integrating the thread pool with the existing custom asynch handling, which I think you offered to do yourself.

**Comment by jonspalmer** [comment]
I've merged this request and then reworked it a little to put the Thread pooling logic entirely in the Configuraiton. It makes testing a whole lot easier and I was able to get good specs around most of the relevant changes.

**Pull request merged**
