### PR TITLE
resolved issues #19 and #20

### PR DESCRIPTION
**Pull request by ghost**
```
* Notifications sent to Airbrake asynchronously by default using a thread pool of configurable size #20
* Stack traces are filtered #19
* Upgraded to Grails 2.1.1
* XML message is logged at debug level
```

### CODE REVIEW

**Comment by jonspalmer** [comment]
I think this pull request needs more work. In particular:
1. we need to continue to support a custom async handler so the user can supply their own implementation (such as a queue)
2. we should still support sending syncronously, helpful for debugging and development mode
3. Needs specs around both async changes and stacktrace filtering.

**Comment by ghost** [comment]
> we need to continue to support a custom async handler so the user can supply their own implementation (such as a queue)

I thought we agreed that I would replace all the custom async stuff a thread pool? I really don't see any value in keeping the custom async stuff given that it's so cumbersome to use and the thread pool is so easy.

> we should still support sending syncronously, helpful for debugging and development mode

OK, do you want the default to be async or sync, i.e. if the thread config param is not specified?

> Needs specs around both async changes and stacktrace filtering.

By specs, you mean unit tests, right?

**Comment by jonspalmer** [comment]
> > we need to continue to support a custom async handler so the user can supply their own implementation (such as a queue)
> 
> I thought we agreed that I would replace all the custom async stuff a thread pool? I really don't see any value in keeping the custom async stuff given that it's so cumbersome to use and the thread pool is so easy.

We should have the option to supply a custom implementation. For example in my apps we're using Jesque queues for all background processing. I want to be able to deliver Airbrake errors using the same approach (where I can configure worker threads dynamically, handle failures etc.). Its important that I only have one source of threads in my app. I'd imagine this is common for anyone with an existing background thread solution.

> > we should still support sending syncronously, helpful for debugging and development mode
> 
> OK, do you want the default to be async or sync, i.e. if the thread config param is not specified?

The Ruby gem supports an 'async' config parameter that is 'false' by default. Maybe we can have it be 'true' in  which case you get the ThreadPool you added or a Closure in which case you use the mechanism I had before.

> By specs, you mean unit tests, right?

Yup unit tests (or specs in Spock's nomenclature)

**Comment by jonspalmer** [comment]
Pull request 22 replaced this

**Pull request closed without merging**
